[theme]
[theme.overrides]
separator = "|"
idle_bg="#0a0b0e"
info_bg="#0a0b0e"
good_bg="#0a0b0e"
warning_bg="#0a0b0e"
critical_bg="#0a0b0e"
separator_fg="#2a2b2e"
separator_bg="#0a0b0e"

[[block]]
block = "temperature"
interval = 30
format = "     TMP $average     "

[[block]]
block = "net"
interval = 10
format = "    {WIFI $ssid|DEVICE $device}     "
inactive_format = "DOWN"

[[block]]
block = "battery"
interval = 10
format = "    BAT $percentage    "
not_charging_format = "   BAT $percentage      "
missing_format = "    BAT $percentage      "
full_format = "    BAT $percentage     "

[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = "    $timestamp.datetime(f:'%a %d %B        %-I:%M %p')    "
