[theme]
[theme.overrides]
separator = "|"
separator_bg="#0a0b0e"
separator_fg="#1a1b1cbb"

idle_bg="#0a0b0c"
idle_fg="#5a5b5c"

info_bg="#0a0b0c"
info_fg="#5a5b5c"

good_bg="#0a0b0c"
warning_bg="#0a0b0c"

critical_bg="#0a0b0c"

[[block]]
block = "net"
interval = 30
format = " $ip "


[[block]]
block = "temperature"
interval = 30
format = " TMP $average "

[[block]]
block = "net"
interval = 10
format = " {WIFI $ssid|DEVICE $device} "
inactive_format = "DOWN"

[[block]]
block = "battery"
interval = 10
format = " BAT $percentage "
not_charging_format = " BAT $percentage "
missing_format = " BAT $percentage "
full_format = " BAT $percentage "

[[block]]
block = "sound"
format = " VOL $volume.eng(w:2) "
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = " $timestamp.datetime(f:'%a %e %B        %-I:%M %p') "
